// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArkp59FInYGIMCgqbKd9yS2YCyyzSS0zY',
    appId: '1:242453460225:web:9b141e25f9e4b060169700',
    messagingSenderId: '242453460225',
    projectId: 'note-app-3ea3b',
    authDomain: 'note-app-3ea3b.firebaseapp.com',
    storageBucket: 'note-app-3ea3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDebOriwp_FcSHDY8Ul7oJoAxivjzdW8uQ',
    appId: '1:242453460225:android:fb4f7387a19693fe169700',
    messagingSenderId: '242453460225',
    projectId: 'note-app-3ea3b',
    storageBucket: 'note-app-3ea3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbXMF5KfTVyPWqWd7fvqQaaDZr7q7JLI',
    appId: '1:242453460225:ios:e88d1e200e89a822169700',
    messagingSenderId: '242453460225',
    projectId: 'note-app-3ea3b',
    storageBucket: 'note-app-3ea3b.appspot.com',
    iosClientId: '242453460225-nv9id1brlqcc9r1urok39n344fiij2ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmbXMF5KfTVyPWqWd7fvqQaaDZr7q7JLI',
    appId: '1:242453460225:ios:e88d1e200e89a822169700',
    messagingSenderId: '242453460225',
    projectId: 'note-app-3ea3b',
    storageBucket: 'note-app-3ea3b.appspot.com',
    iosClientId: '242453460225-nv9id1brlqcc9r1urok39n344fiij2ps.apps.googleusercontent.com',
    iosBundleId: 'com.example.nodeApp',
  );
}
